### Create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "jovem@gmail.com",
  "password": "password"
}

### Login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "jovem@gmail.com",
  "password": "password"
}

### Find one user
GET http://localhost:3000/auth/2

### Find all users with given email
GET http://localhost:3000/auth?email=xablau@gmail.com

### Update one user
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "xablau@gmail.com"
}

### Delete one user
DELETE http://localhost:3000/auth/1

### Get current logged in user
GET http://localhost:3000/auth/whoami
